version: "3"
services:
  # consul : use bitnami/consul image instead of hashicorp/consul
  consul:
    image: bitnami/consul:1-debian-11
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 100M
        #reservations:
        #  cpus: '0.2'
        #  memory: 20M
    restart: always
    volumes:
     - ./consul:/opt/bitnami/consul/conf:ro
    ports:
      - "8300:8300"
      - "8301:8301"
      - "8301:8301/udp"
      - "8500:8500"
      - "8600:8600/tcp"
      - "8600:8600/udp"
    networks:
      - rabbitmq_cluster_network
      
  # haproxy : depends on rabbit 
  haproxy:
    #image: dockercloud/haproxy
    image: haproxy:lts-alpine
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 100M
        #reservations:
        #  cpus: '0.2'
        #  memory: 20M
    restart: always
    environment:
      - MODE="tcp"
    volumes:
      - ./haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "15672:15672"
      - "5672:5672"
      - "1883:1883"
      - "61613:61613"
      - "15674:15674"
      - "15675:15675"
      # HAProxy Statistics Page
      - "1936:1936"
    links:
      - rabbit
    networks:
      - rabbitmq_cluster_network
    depends_on:
      - consul

  # rabbit : depends on consul (peer discovery)
  rabbit:
    #deploy:
    image: rabbitmq:3-management-alpine
    deploy:
      # default replica is 1
      #replicas: 1
      resources:
        limits:
          cpus: '1'
          memory: 256M
        #reservations:
        #  cpus: '0.2'
        #  memory: 20M
    restart: always
    environment:
      - RABBITMQ_ERLANG_COOKIE=${RABBITMQ_ERLANG_COOKIE}
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
      - RABBITMQ_DEFAULT_VHOST=${RABBITMQ_DEFAULT_VHOST}
    # bind conf/rabbitmq.conf file, create dynamic volume
    volumes:
      - ./rabbit/:/etc/rabbitmq/
      - /var/lib/rabbitmq
    expose:
      - 15672
      - 5672
      - 5671
      - 1883
      - 8883
      - 15671
    command: /bin/sh -c "sleep 10; rabbitmq-server;"
    tty: true
    networks:
      - rabbitmq_cluster_network
    depends_on:
      - consul

#volumes:
#  rabbit_mnesia:
#    driver: local

networks:
  rabbitmq_cluster_network:
    driver: bridge

